---
title: "leapQ_acceptability"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(sciplot)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
vaPalette <- c("#FCC6BB", "#F54927", "#9C2007", "#440E03")
gPal <- c("#B9E615","#5E15E6","#F78D02", "#009E73")

# scale_fill_manual(values = vaPalette)
# valPal <- c("#F4320B")

this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

d <- read.csv("../data/combined_leap_MS_jun02.csv")
length(unique(d$Participant)) #215
names(d)
```

# Baseline model
```{r}
baseline <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition + (1|Participant) + (1|Name), data = d)

d$Valence <- as.factor(d$Valence)
str(d$Valence)

```


# AOA 
```{r}
m.aoa <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*aoa + (1|Participant) + (1|Name), data = d)

anova(baseline,m.aoa)
```

# Family Learning

```{r}
m.fl <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*learn_family + (1|Participant) + (1|Name), data = d)

anova(baseline,m.fl)

```


# RP 

```{r}
m.rp <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*prof_read + (1|Participant) + (1|Name), data = d)

anova(baseline,m.rp)
```

# Daily Exposure

```{r}
m.de <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*use_pct + (1|Participant) + (1|Name), data = d)

anova(baseline,m.de)
```

# Family Imersion

```{r, eval=FALSE}
m.if <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*immers_family + (1|Participant) + (1|Name), data = d)

summary(m.if)

anova(baseline,m.if)
```

# School Imersion

```{r, eval=FALSE}
m.is <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*immers_school + (1|Participant) + (1|Name), data = d)

summary(m.is)

anova(baseline,m.is)
```


# Country Imersion

```{r, eval=FALSE}
m.ic <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*immers_country + (1|Participant) + (1|Name), data = d)

summary(m.ic)

anova(baseline,m.ic)
```

# Family Use

```{r, eval=FALSE}
m.fu <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*use_family + (1|Participant) + (1|Name), data = d)

anova(baseline,m.fu)
```

# Use Self "class or self-instruction"

```{r, eval=FALSE}
m.se <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*use_self + (1|Participant) + (1|Name), data = d)

anova(baseline,m.se)
```

# Self LEarning

```{r, eval=FALSE}
m.sl <- lmer(SliderResponse ~ LexicalType*Valence*ContextCondition*learn_self + (1|Participant) + (1|Name), data = d)

anova(baseline,m.sl)
```
