---
title: "At-Issue judgments W&R stimuli: Analysis"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) 
library(stringr)
library(textstem)
library(tidyverse)
library(broom.mixed)  # for tidy()
library(ggeffects)
library(lattice)

theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

d <- read.csv("../data/processed.csv")
```

```{r}
d <- d %>% 
  mutate(Word = as.factor(Word),
         Participant = as.factor(Participant),
         Valence = as.factor(Valence),
         Response = as.numeric(Response))

m <- lmer(Response ~ Valence + (1|Word) + (1+Valence|Participant), data = d)
summary(m)
```

```{r}
d <- d %>% 
  filter(Valence %in% c("positive","negative")) %>% 
  mutate(Word = as.factor(Word),
         Participant = as.factor(Participant),
         Valence = as.factor(Valence),
         Response = as.numeric(Response),
         cValence = mean)

m <- lmer(Response ~ Valence + (1|Word) + (1+Valence|Participant), data = d)
summary(m)
```