---
title: "Bilingual Assholes: preprocessing"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

# Read in the results
d.it <- read.pcibex("../data/results_it.csv")
d.it["Language"] <- "Italian"
nrow(d.it)
table(d.it$Group)


d.eng <- read.pcibex("../data/results_eng.csv")
d.eng["Language"] <- "English"
nrow(d.eng)
table(d.eng$Group)

d <- rbind(d.it,d.eng)
nrow(d)
# Assign participant number
d$Participant <- as.integer(factor(d$MD5.hash.of.participant.s.IP.address))
length(unique(d$Participant))

names(d)
```




```{r}
# Separate out demographic information
demo <- d %>% 
    filter((Label == "demo") &
             (!Parameter %in% c("_Trial_","_Header_"))) %>% 
    dplyr::select(Participant,Parameter,Value) %>% 
    pivot_wider(
        names_from = Parameter,
        values_from = Value,
        names_prefix = "Demo_"
      )

lq <- d %>% 
    filter((Label == "leap-q") &
             (!Parameter %in% c("_Trial_","_Header_"))) %>% 
    dplyr::select(Participant,Parameter,Value) %>% 
    pivot_wider(
        names_from = Parameter,
        values_from = Value,
        names_prefix = "LQ_"
      )
names(d)

part.lang <- na.omit(unique(d[,c("Participant","Language")]))

nrow(part.lang)

d.rating <- d %>% 
    filter((Label == "rating_task") & 
             (PennElementType %in% c("Scale","Var"))) %>% 
      pivot_wider(
          names_from = PennElementName,
          values_from = Value
        )  %>% 
  tidyr::fill(Participant)

# extract non-NA words and scores
words <- d.rating %>%
  filter(!is.na(Word)) %>%
  select(Participant, Word)

scores.v <- d.rating %>%
  filter(!is.na(likert_valence)) %>%
  select(likert_valence)
scores.a <- d.rating %>%
  filter(!is.na(likert_arousal)) %>%
  select(likert_arousal)

# combine by position
d.rating.good <- bind_cols(words, scores.a,scores.v)
d.rating.good <- left_join(d.rating.good,part.lang, by = "Participant")

View(d.rating.good)

# View(result

View(d.rating.good)
nrow(d.rating)
length(unique(d.rating$Participant))
length(unique(d.rating$Word))

table(d.rating$Language)
      


d.expl <- d %>% 
    filter((Label == "expletive_test") &
             (PennElementType == "Scale")) %>% 
    dplyr::select(Participant,Label,Value,Number,TrialType,Valence,LexicalType,ContextCondition,Group,Name,Language) %>% 
    rename(SliderResponse = Value) %>% 
  # remove trailing whitespace
  mutate(across(where(is.character), str_trim))


str(d.expl$TrialType)

fillers <- d.expl %>% 
  filter(TrialType == "fillers")

nrow(fillers)

df_combined <- full_join(demo,lq, d.rating, d.expl, by = "Participant")

# Collapse List-columns, 
# convert c(3, 4, 5) to "3;4;5"
# df_combined <- df_combined |>
  # dplyr::mutate(across(where(is.list),
                       # ~ sapply(., paste, collapse = ";")))

# df_combined <- full_join(val,df_combined, by = "Word")
View(d)
```


```{r}

# Write to .csv not aggregating over participants
write.csv(df_combined,"../data/processed_total.csv")
write.csv(lq,"../data/processed_lq.csv")
write.csv(d.rating.good,"../data/processed_rating.csv")
write.csv(d.expl,"../data/processed_expl.csv")

```