---
title: "Bilingual Assholes Total: Analysis"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) 
library(stringr)
library(textstem)
library(tidyverse)
library(broom.mixed)  # for tidy()
library(ggeffects)
library(lattice)

theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

df_s1 <- read.csv("../../01_experiment/data/processed_rating.csv")
df_s1["Study"] <- "Study1"
length(unique(df_s1$Participant))

df_s2 <- read.csv("../../02_experiment/data/data_rating_exclusions.csv")
df_s2["Study"] <- "Study2"
df_s2$X.1 <- NULL
length(unique(df_s2$Participant))
# offset the participant numbering
df_s2$Participant <- df_s2$Participant + max(df_s1$Participant)

names(df_s1)
names(df_s2)

d <- rbind(df_s1,df_s2)
length(unique(d$Participant)) # 458

# d_high_prof <- inner_join(d,prof, by = "Participant")
pairs <- read.csv("../data/word_pairs.csv")

length(unique(d$Word))
nrow(d)
names(d)
str(d$Language)
d$Language.n <- as.numeric(d$Language)
summary(d$Langauge.)
```

```{r}
d <- d %>%
  mutate(
    Language.n = ifelse(Language == "English", 0, 1)
  )

d <- d %>% 
  filter(TrialType == "test") %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         ContextCondition = as.factor(ContextCondition),
         SliderResponse = as.numeric(SliderResponse),
         cLanguage = Language.n-mean(Language.n))


m <- lmer(SliderResponse ~ ContextCondition*cLanguage + (1+ContextCondition*cLanguage|Name) + (1+ContextCondition|Participant), data = d)
summary(m)
```


```{r}
d <- d %>% 
  filter(Valence %in% c("positive","negative")) %>% 
  mutate(Word = as.factor(Word),
         Participant = as.factor(Participant),
         Valence = as.factor(Valence),
         Response = as.numeric(Response),
         cValence = mean)

m <- lmer(Response ~ Valence + (1|Word) + (1+Valence|Participant), data = d)
summary(m)
```