---
title: "Bilingual Assholes Total Data: Expl Analysis"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(sciplot)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
vaPalette <- c("#FCC6BB", "#F54927", "#9C2007", "#440E03")
gPal <- c("#B9E615","#5E15E6","#F78D02", "#009E73")

# scale_fill_manual(values = vaPalette)
# valPal <- c("#F4320B")

this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

df_s1 <- read.csv("../../01_experiment/data/processed_expl.csv")
df_s1["Study"] <- "Study1"
length(unique(df_s1$Participant))

df_s2 <- read.csv("../../02_experiment/data/data_exclusions.csv")
df_s2["Study"] <- "Study2"
df_s2$X.1 <- NULL
length(unique(df_s2$Participant))
# offset the participant numbering
df_s2$Participant <- df_s2$Participant + max(df_s1$Participant)

names(df_s1)
names(df_s2)

d <- rbind(df_s1,df_s2)
length(unique(d$Participant)) # 458
```



# Main model

```{r}
d <- d %>%
  mutate(
    Nativeness.n = ifelse(Nativeness == "L1", 0, 1)
  )

d <- d %>% 
  # filter(TrialType == "test") %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         ContextCondition = as.factor(ContextCondition),
         SliderResponse = as.numeric(SliderResponse),
         cNativeness = Nativeness.n-mean(Nativeness.n))

m.s <- lmer(SliderResponse ~ ContextCondition + (1+ContextCondition|Name) + (1+ContextCondition|Participant), data = d)
summary(m.s)

m.c.n <- lmer(SliderResponse ~ ContextCondition*Nativeness + (1+ContextCondition|Name) + (1+ContextCondition|Participant), data = d)
summary(m.c.n)



m.l <- lmer(SliderResponse ~ ContextCondition*Nativeness*StudyLanguage + (1+ContextCondition|Name) + (1+ContextCondition|Participant), data = d)
summary(m.l)

anova(m.c.n,m.l)
```


```{r}

levels(d$LexicalType)
d <- d %>%
  mutate(
    LexicalType.n = ifelse(LexicalType == "adj", 0, 1)
  )

dcen <- d %>% 
  filter(TrialType == "test") %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         LexicalType = as.factor(LexicalType),
         ContextCondition = as.factor(ContextCondition),
         SliderResponse = as.numeric(SliderResponse),
         cNativeness = Nativeness.n-mean(Nativeness.n),
         cLexicalType = LexicalType.n-mean(LexicalType.n))


m2 <- lmer(SliderResponse ~ cLexicalType*ContextCondition*Nativeness + (1+ContextCondition|Name) + (1+ContextCondition+cLexicalType|Participant), data = dcen)

summary(m2)

```




# Valence?


```{r}
d <- d %>%
  mutate(
    LexicalType.n = ifelse(LexicalType == "adj", 0, 1),
    Valence.n = ifelse(Valence == "neg", 0, 1)
  )

dcen <- d %>% 
  filter(Valence %in% c("pos","neg")) %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         ContextCondition = as.factor(ContextCondition),
         Response = as.numeric(SliderResponse),
         cValence = Valence.n-mean(Valence.n),
         cLexicalType = LexicalType.n-mean(LexicalType.n))

m.s <- lmer(Response ~ cLexicalType*ContextCondition + (1|Name) + (1+cLexicalType+ContextCondition|Participant), data = dcen)
summary(m.s)

m.c <- lmer(Response ~ cValence*cLexicalType*ContextCondition + (1|Name) + (1+cValence+cLexicalType+ContextCondition|Participant), data = dcen)
summary(m.c)

anova(m.s,m.c)



```



# Does language explain more variance?
- No
```{r}
m.c.l <- lmer(Response ~ Nativeness*cValence*cLexicalType*ContextCondition + (1|Name) + (1+cValence+cLexicalType+ContextCondition|Participant), data = dcen)
summary(m.c.l)

anova(m.c, m.c.l)
```

# Valence and language?
```{r}
m.v.l <- lmer(Response ~ Nativeness*cValence + (1|Name) + (1+cValence|Participant), data = dcen)
summary(m.v.l)
```


## But in the TO condition
```{r}
to <- d %>% 
  filter(ContextCondition == "TO") %>% 
  filter(Valence %in% c("pos","neg")) %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         ContextCondition = as.factor(ContextCondition),
         Response = as.numeric(SliderResponse),
         cValence = Valence.n-mean(Valence.n),
         cLexicalType = LexicalType.n-mean(LexicalType.n))

m.to <- lmer(Response ~ Nativeness*Valence*cLexicalType + (1|Name) + (1+cValence+cLexicalType|Participant), data = to)

summary(m.to)

```



#Negative only

```{r}

levels(d$LexicalType)
d <- d %>%
  mutate(
    LexicalType.n = ifelse(LexicalType == "adj", 0, 1)
  )

dcen <- d %>% 
  filter((TrialType == "test") & (Valence == "neg")) %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         LexicalType = as.factor(LexicalType),
         ContextCondition = as.factor(ContextCondition),
         SliderResponse = as.numeric(SliderResponse),
         cNativeness = Nativeness.n-mean(Nativeness.n),
         cLexicalType = LexicalType.n-mean(LexicalType.n))


m4 <- lmer(SliderResponse ~ cLexicalType*ContextCondition + (1+ContextCondition|Name) + (1+ContextCondition+cLexicalType|Participant), data = dcen)

summary(m4)

```

# Positive

```{r}

levels(d$LexicalType)
d <- d %>%
  mutate(
    LexicalType.n = ifelse(LexicalType == "adj", 0, 1)
  )

dcen <- d %>% 
  filter((TrialType == "test") & (Valence == "pos")) %>% 
  mutate(Name = as.factor(Name),
         Participant = as.factor(Participant),
         LexicalType = as.factor(LexicalType),
         ContextCondition = as.factor(ContextCondition),
         SliderResponse = as.numeric(SliderResponse),
         cNativeness = Nativeness.n-mean(Nativeness.n),
         cLexicalType = LexicalType.n-mean(LexicalType.n))


m5 <- lmer(SliderResponse ~ cLexicalType*ContextCondition + (1+ContextCondition|Name) + (1+ContextCondition+cLexicalType|Participant), data = dcen)

summary(m5)

```